name: JMeter Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    # Manual trigger option

jobs:
  jmeter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz

      - name: Run Standard Test Plan
        run: |
          ./apache-jmeter-5.6.3/bin/jmeter -n -t DemoQA-Performance-Test-Plan.jmx -l standard_results.jtl -j jmeter_standard.log

      - name: Run CSV Test Plan
        run: |
          ./apache-jmeter-5.6.3/bin/jmeter -n -t DemoQA-Performance-Test-Plan-CSV.jmx -l csv_results.jtl -j jmeter_csv.log

      - name: Upload JMeter results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: |
            *.jtl
            *.log
